theme = "catppuccin-mocha"
diff_view = "side-by-side"
ignore_whitespace = false
mouse = true
leader = ";"
comment_vim = true
relative_line_numbers = false

comment_types = [
  { id = "note", definition = "note for reviewers", color = "#b2b2b2" },
  { id = "question", definition = "ask for clarification", color = "#a7ecf3" },
  { id = "issue", definition = "problems to fix", color = "#f61a1a" },
  { id = "suggestion", definition = "possible improvements", color = "#f6972a" },
  { id = "nit", label = "nitpick", definition = "small optional tweaks", color = "#f7f12a" },
  { id = "praise", definition = "positive feedback", color = "#25f230" },
]
